### ISSUE TITLE
Missing Paper

### ISSUE THREAD

**Issue by AslanDevbrat** [ContinualAI/colab#26]
The link given in the  `CL_via_PNN.ipynb ` to its related Paper is not working. Can Update that link or can you share the related paper's link with me?

**Comment by AntonioCarta** [comment]
There is a typo, this is the correct link: [https://arxiv.org/abs/1606.04671.pdf](https://arxiv.org/abs/1606.04671.pdf)

**Comment by AslanDevbrat** [comment]
When I click on the link given in the notebook it's not opening. The link you shared just now that's working. If possible please replace that link in the notebook
